server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-512-bit-secret-key-must-be-at-least-32-characters-long

eureka:
  client:
    service-url:
      defaultZone: http://admin:password@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    appname: product-service
    instance-id: ${spring.application.name}:${random.value}